%% --- Save Trained Models to Disk ---
%
% Saves all trained model variables into a single .mat file.
% Call this once after training to avoid retraining every run.
%
% Usage:
%   save_models('trained_models.mat', transitionProbs, vocab, word2idx, ...
%               trigramModel, coMatrix, coVocab, coWord2idx)

function save_models(filename, transitionProbs, bigramVocab, bigramWord2idx, ...
                     trigramModel, coMatrix, coVocab, coWord2idx)

    fprintf('Saving models to "%s"...\n', filename);

    save(filename, ...
         'transitionProbs', ...
         'bigramVocab', ...
         'bigramWord2idx', ...
         'trigramModel', ...
         'coMatrix', ...
         'coVocab', ...
         'coWord2idx');

    info = dir(filename);
    fprintf('Done. File size: %.2f MB\n', info.bytes / 1e6);
end